-- MySQL Script generated by MySQL Workbench
-- mer. 11 avril 2018 10:08:48 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wcs_taekwondo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wcs_taekwondo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wcs_taekwondo` DEFAULT CHARACTER SET utf8 ;
USE `wcs_taekwondo` ;

-- -----------------------------------------------------
-- Table `wcs_taekwondo`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wcs_taekwondo`.`category` ;

CREATE TABLE IF NOT EXISTS `wcs_taekwondo`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wcs_taekwondo`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wcs_taekwondo`.`gallery` ;

CREATE TABLE IF NOT EXISTS `wcs_taekwondo`.`gallery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gallery_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_gallery_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `wcs_taekwondo`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wcs_taekwondo`.`gallery_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wcs_taekwondo`.`gallery_image` ;

CREATE TABLE IF NOT EXISTS `wcs_taekwondo`.`gallery_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gallery_id` INT NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gallery_image_gallery1_idx` (`gallery_id` ASC),
  CONSTRAINT `fk_gallery_image_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `wcs_taekwondo`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
