-- MySQL Script generated by MySQL Workbench
-- ven. 13 avril 2018 10:56:43 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wcs_taekwondo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wcs_taekwondo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wcs_taekwondo` DEFAULT CHARACTER SET utf8 ;
USE `wcs_taekwondo` ;

-- -----------------------------------------------------
-- Table `wcs_taekwondo`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wcs_taekwondo`.`event` ;

CREATE TABLE IF NOT EXISTS `wcs_taekwondo`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_event` DATETIME NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  `description` TEXT NOT NULL,
  `picture` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
